const http = require('http');
const fs = require('fs');
const path = require('path');
const { URL } = require('url');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.ico': 'image/x-icon',
};

function parseDepots(raw) {
  return [...new Set(String(raw || '').split(/[\n,]/).map((id) => id.trim()).filter(Boolean))];
}

function steamManifest(data) {
  const depots = parseDepots(data.depots);
  const depotLines = depots.length
    ? depots.map((id) => `\t\t"${id}"\t\t"${data.buildId}"`).join('\n')
    : `\t\t"${data.appId}"\t\t"${data.buildId}"`;

  return `"AppState"
{
\t"appid"\t\t"${data.appId}"
\t"Universe"\t\t"1"
\t"name"\t\t"${data.name}"
\t"StateFlags"\t\t"4"
\t"installdir"\t\t"${data.installdir}"
\t"LastUpdated"\t\t"0"
\t"LastPlayed"\t\t"0"
\t"SizeOnDisk"\t\t"0"
\t"buildid"\t\t"${data.buildId}"
\t"InstalledDepots"
\t{
${depotLines}
\t}
\t"MountedConfig"
\t{
\t\t"BetaKey"\t\t"${data.branch}"
\t}
}`;
}

function luaLauncher(data) {
  return `-- Generated by SteamManiLua
local game = {
  appid = ${Number(data.appId)},
  name = "${data.name}",
  installdir = "${data.installdir}",
  executable = "${data.exe}",
  branch = "${data.branch}"
}

function launch(basePath)
  local target = basePath .. "/" .. game.installdir .. "/" .. game.executable
  print("Launching: " .. target)
  return os.execute('"' .. target .. '"')
end

return {
  game = game,
  launch = launch
}
`;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', (chunk) => {
      body += chunk;
      if (body.length > 1_000_000) {
        reject(new Error('Payload too large'));
      }
    });
    req.on('end', () => resolve(body));
    req.on('error', reject);
  });
}

function sendJson(res, status, payload) {
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(payload));
}

function normalizeInput(input) {
  const appId = String(input.appId || '').trim();
  if (!/^\d+$/.test(appId)) {
    return { error: 'App ID must be numeric.' };
  }

  const installdir = String(input.installdir || 'Game').trim() || 'Game';

  return {
    appId,
    name: String(input.name || 'Unnamed Game').trim() || 'Unnamed Game',
    buildId: String(input.buildId || '0').trim() || '0',
    branch: String(input.branch || 'public').trim() || 'public',
    installdir,
    exe: String(input.exe || 'game.exe').trim() || 'game.exe',
    depots: String(input.depots || ''),
  };
}

function serveStatic(req, res, pathname) {
  const routePath = pathname === '/' ? '/index.html' : pathname;
  const filePath = path.join(ROOT, routePath);
  if (!filePath.startsWith(ROOT)) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }

  fs.readFile(filePath, (err, content) => {
    if (err) {
      res.writeHead(err.code === 'ENOENT' ? 404 : 500, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end(err.code === 'ENOENT' ? 'Not found' : 'Server error');
      return;
    }

    const ext = path.extname(filePath);
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
    res.end(content);
  });
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);

  if (req.method === 'POST' && url.pathname === '/api/generate') {
    try {
      const rawBody = await readBody(req);
      const data = normalizeInput(JSON.parse(rawBody || '{}'));
      if (data.error) {
        sendJson(res, 400, data);
        return;
      }

      const manifest = steamManifest(data);
      const lua = luaLauncher(data);
      sendJson(res, 200, {
        appId: data.appId,
        manifest,
        lua,
        manifestFilename: `appmanifest_${data.appId}.acf`,
        luaFilename: `${data.installdir.toLowerCase().replace(/\s+/g, '_') || 'launcher'}.lua`,
      });
    } catch (error) {
      sendJson(res, 400, { error: 'Invalid request payload.' });
    }
    return;
  }

  serveStatic(req, res, url.pathname);
});

server.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`SteamManiLua running at http://localhost:${PORT}`);
});
